runtime: python37
entrypoint: gunicorn -b :$PORT lmnop_project.wsgi

handlers:
- url: /static
  static_dir: www/static/

- url: /.*
  script: auto

env_variables:
  POSTGRE_PW: iKlF9eCqJpILnHbE

beta_settings:
  cloud_sql_instances: lmnop-295416:us-central1:lmnop-5432
